version: 0.2

env:
  parameter-store:
    USERNAME: /myapp/docker-credentials/username
    PASSWORD: /myapp/docker-credentials/password
    KEY:  /myapp/mongodb/url
    SID: /myapp/accountSid/id
    TOKEN: /myapp/authtoken/token
    NUMBER: /myapp/twiphonenumber/number
    
phases:
  install:
    runtime-versions:
      nodejs: latest
    commands:
      - node --version
      - echo "installed node "
    # steps:
  pre_build:
    commands:
      - npm install
      - echo "dependencies installed"
  Snyk security scan:
     commands:
      - sudo npm install -g snyk
      - snyk auth
      - snyk --version    
  build:
    commands:
      - docker build . -t godfredji123/management-system-app-prod:latest --build-arg MONGODB_URL_PARAM=$KEY --build-arg ACCOUNT_SID_PARAM=$SID --build-arg AUTH_TOKEN_PARAM=$TOKEN --build-arg TWI_PHONE_NUMBER_PARAM=$NUMBER
  post_build:
    commands:
      - echo "waiting right now"
      - docker login -u $USERNAME -p $PASSWORD
      - docker push godfred123/management-system-app-prod:latest
artifacts:
  files:
    - '**/*'
  base-directory: "./"
  name: resqplate
  discard-paths: no
